version: '3.9'

services:
  api:
    build: .
    container_name: fastapi_backend
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  streamlit:
    build: .
    container_name: streamlit_frontend
    command: streamlit run app/app.py --server.port 8501 --server.enableCORS false
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - api
